### PR TITLE
something else than yaourt

### PR DESCRIPTION
**Pull request by noraj**
Yaourt is a dangerous deprecated pacman wrapper.
ArchLinux even remvoed it's from the wiki to avodi dangerous downfalls due to its past popularity.
Suggest any other pacman wrapper with AUR support like pikaur, yay or whatever: https://wiki.archlinux.org/index.php/AUR_helpers#Pacman_wrappers

### CODE REVIEW

**Comment by cytopia** [comment]
@noraj thanks for pointing that out. Can you go ahead and update README.md as well.

Also I just looked into the various alternatives and seen from a GitHub stars perspective [yay](https://github.com/Jguer/yay) is the current favorite. Would you agree with that or am I mistaken here?

**Comment by noraj** [comment]
> Also I just looked into the various alternatives and seen from a GitHub stars perspective [yay](https://github.com/Jguer/yay) is the current favorite. Would you agree with that or am I mistaken here (have used neither of them yet)?

It may not be the better one but yes yay has more "fame" because it has a cool name. I'll replace yaourt by yay so.

**Comment by noraj** [comment]
Idk know teh right place to talk about that, but just to let you know there was a new tool released a month ago with a similar goal and exactly the same name [pwncat](https://github.com/calebstewart/pwncat). I [contacted the author](https://github.com/calebstewart/pwncat/issues/18) to let them know but without an answer for 1 week. You maybe want to try to reach them.
There is probably not much you can do but as I said it's just to let you know there is a copy-cat around here.

**Comment by cytopia** [comment]
Thanks for the info.

**Pull request merged**
